branches:
  only:
    - master

language: node_js

matrix:
  include:
    - os: linux
      dist: xenial
      services:
        - xvfb

    - os: osx

    # - os: windows
    #   env:
    #     - YARN_GPG=no # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9

node_js:
  - 10

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn test

deploy:
  provider: script
  script: yarn ci:publish
  skip_cleanup: true
  on:
    tags: true
    branch: master
