branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/

language: node_js

node_js:
  - 10

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - yarn test

jobs:
  include:
    - name: Mac tests
      stage: test
      os: osx

    - name: Linux tests
      stage: test
      os: linux
      dist: xenial
      services:
        - xvfb

    - name: Windows tests
      os: windows
      env:
        - YARN_GPG=no # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
      filter_secrets: false # https://travis-ci.community/t/windows-instances-hanging-before-install/250/15
      before_install:
        - unset NPM_TOKEN # https://travis-ci.community/t/windows-instances-hanging-before-install/250/15
        - ./scripts/ci-windows-pre-install.sh
      install:
        - yarn --network-timeout 1000000
      script:
        - yarn test -- --forceExit # until we figure out why windows builds hang after tests pass

    - name: Publish to npm
      stage: deploy
      script: skip
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      deploy:
        provider: script
        script: yarn ci:publish
        skip_cleanup: true
        on:
          tags: true
          branch: master
