language: node_js

os:
  - linux
  - osx
  - windows

node_js:
  - 10

# needed for windows travis, which gets stuck after running tests
# https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
env:
  - YARN_GPG=no

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install -y vcredist2015; fi

# needed to run electron in travis
# https://electronjs.org/docs/tutorial/testing-on-headless-ci#travis-ci
addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - yarn
  - yarn add -W electron@latest
  - yarn which electron
  - yarn electron -v
  - yarn electron ./packages/corvid-cli/src/commands/open-editor.js

script:
  - yarn test