branches:
  only:
    - master

language: node_js

node_js:
  - 10

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - yarn test

jobs:
  include:
    - name: Mac tests
      stage: test
      os: osx
    
    - name: Linux tests
      stage: test
      os: linux
      dist: xenial
      services:
        - xvfb

    # - name: Windows tests
    #   os: windows
    #   env:
    #     - YARN_GPG=no # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9

    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: yarn ci:publish
        on:
          tags: true
          branch: master  