language: node_js

os:
  - linux
  - osx
  - windows

node_js:
  - 8

cache:
  yarn: true

# needed for windows travis, which gets stuck after running tests
# https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
env:
  - YARN_GPG=no

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

jobs:
  include:
    - name: "lint"
      script:
        - yarn lint
    - name: "test"
      script:
        - yarn test