module.exports.socketActions = {
    DISCONNECT: 'disconnect',
    GET_VERSION: 'GET_VERSION',
    IS_CLONE_MODE: 'IS_CLONE_MODE',
    GET_DOCUMENT: 'GET_DOCUMENT',
    OVERRIDE_DOCUMENT: 'OVERRIDE_DOCUMENT',
    GET_CODE: 'GET_CODE',
    UPDATE_CODE: 'UPDATE_CODE'
}