// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Path = require("path");
var CorvidLocalTestUtils = require("corvid-local-test-utils");
var Testkit = require("corvid-local-site/testkit");
var Testkit$1 = require("corvid-local-server/src/testkit");

function initSite(siteItems) {
  return CorvidLocalTestUtils.initTempDir(siteItems).then((function (localSite) {
                Fs.writeFileSync(Path.join(localSite, ".corvidrc.json"), "", "utf8");
                return Promise.resolve(localSite);
              }));
}

var server = {
  startInEditMode: (function (prim) {
      return Testkit$1.startInEditMode(prim);
    }),
  startInCloneMode: (function (prim) {
      return Testkit$1.startInCloneMode(prim);
    })
};

var localTestkit = {
  initSite: initSite,
  server: server,
  siteCreators: CorvidLocalTestUtils.siteCreators,
  localSiteBuilder: Testkit.localSiteBuilder
};

var $$default = localTestkit;

exports.localTestkit = localTestkit;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* localTestkit Not a pure module */
