name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: 'https://registry.npmjs.org'
    - name: Install
        run: yarn
    - name: Test
        run: ./node_modules/.bin/xvfb-maybe yarn test:noe2e
    - run: yarn ci:publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}