name: Test on Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "*/59 23 * * *"

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install
        run: yarn
      - name: Test
        run: ./node_modules/.bin/xvfb-maybe yarn test
